site_name: ProvisionGenie
site_description: Read the full documentation for ProvisionGenie ðŸ§ž to provision custom-tailored Microsoft Teams teams based on your user's needs
site_url: https://provisiongenie.com/
nav:
  - ProvisionGenie: 
    - Home: 'index.md'
    - Admin fact sheet: 'adminfactsheet.md'
    - Cost estimation: 'costestimation.md'
    - Architecture decisions: 'architecturedecisions.md'
    - Design Guide: 'designguide.md'
    - Accessibility guide: 'accessibilityguide.md'
  - Core components:
    - Solution Overview: 'corecomponents/solutionoverview.md'
    - Canvas App: 
      - Overview: 'corecomponents/canvasapp.md'
      - How to build: 'corecomponents/howtobuildthecanvasapp.md'
    - Dataverse: 
      - Overview: 'corecomponents/dataverse.md'
    - Logic Apps: 
      - Overview: 'corecomponents/logicapps.md'
    - Language Packs:
      - Overview: 'corecomponents/languagepacks.md'



  - Deployment guide:
    - Clean install:
      - Start: 'deploymentguide/index.md'
      - Copied values: 'deploymentguide/copiedvalues.md'
      - 0. Fork and clone this repository: 'deploymentguide/0-forkclone.md'
      - 1. Register application in Azure AD: 'deploymentguide/1-registerapp.md'
      - 2. Import Dataverse solution: 'deploymentguide/2-importsolution.md'
      - 3. Deploy Azure resources: 'deploymentguide/3-deployazureresources.md'
      - 4. Add ProvisionGenie to Teams: 'deploymentguide/4-addtoteams.md'
      - 5. Post Deployment cleanup: 'deploymentguide/5-postdeploycleanup.md'
      - 6. Known Issues: 'deploymentsguide/6-knownissues.md'
    - Upgrade: 
      - Upgrade v1.0.0 --> v2.0.0: 'deploymentguide/upgradev100v200.md'
  - About:
    - Release Notes: 'about/releasenotes.md'
    - Roadmap: 'about/roadmap.md'
    - Sessions: 'about/sessions.md'
    - Developers: 'about/developers.md'
plugins:
    - search
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    scheme: default
  logo: media/site/logo.svg
  favicon: media/site/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
extra_css:
  - 'css/styles.css'
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.snippets
  - def_list
  - attr_list
extra:
  generator: false
repo_url: https://github.com/ProvisionGenie/ProvisionGenie
edit_uri: blob/main/docs/docs